# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMk3mO-FU22x6_h7MkmPxbql-DaiCsd9
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd "/content/drive/MyDrive/DR src"

!pip install -r requirements.txt
!pip install pyngrok

from pyngrok import ngrok
ngrok.kill()
ngrok.set_auth_token("3JEb3DvvRSHdNKWR7KHU4CzlvTw_6GwoQAFbDKhV9p56uBvkM")
!pkill -9 -f uvicorn
!nohup uvicorn inference_api:app --host 0.0.0.0 --port 8000 &
public_url = ngrok.connect(8000)
print(public_url)

!cat nohup.out

!tail -20 nohup.out

!ls
!ls checkpoints