import { useState, useRef, useEffect, useCallback } from "react";
import jsPDF from "jspdf";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

// ─── DATA ───────────────────────────────────────────────────────────────────
// ─── PDF REPORT GENERATION (real PDF, embeds actual images + results) ───────
function generatePdfReport(results, imgSrc, G) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = 50;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("NETRA AI — Clinical Screening Report", margin, y);
  y += 16;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Rural PHC Diabetic Retinopathy Screening · SIH 26038", margin, y);
  doc.text(new Date().toLocaleString(), pageW - margin, y, { align: "right" });
  y += 8;
  doc.setDrawColor(180);
  doc.line(margin, y, pageW - margin, y);
  y += 24;

  // Grade result box
  doc.setFillColor(245, 245, 245);
  doc.rect(margin, y, pageW - margin * 2, 60, "F");
  doc.setTextColor(20);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("AI GRADING RESULT", margin + 10, y + 16);
  doc.setFontSize(15);
  doc.text(`Grade ${results.grade}: ${G.name}`, margin + 10, y + 36);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Confidence: ${(results.confidence * 100).toFixed(1)}%   ·   Triage: ${G.urgency}`, margin + 10, y + 50);
  y += 80;

  // Images row (Original, Enhanced, Vessels, Grad-CAM)
  const imgs = [
    { label: "Original", src: imgSrc },
    { label: "CLAHE Enhanced", src: results.enhanced },
    { label: "Frangi Vessels", src: results.vessels },
    { label: "Grad-CAM", src: results.heatmap },
  ];
  const imgSize = (pageW - margin * 2 - 30) / 4;
  imgs.forEach((im, i) => {
    const x = margin + i * (imgSize + 10);
    try {
      doc.addImage(im.src, "JPEG", x, y, imgSize, imgSize);
    } catch (e) { /* skip if image fails to embed */ }
    doc.setFontSize(7);
    doc.setTextColor(80);
    doc.text(im.label, x + imgSize / 2, y + imgSize + 10, { align: "center" });
  });
  y += imgSize + 26;

  // Clinical recommendation
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(20);
  doc.text("CLINICAL RECOMMENDATION", margin, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const actionLines = doc.splitTextToSize(G.action, pageW - margin * 2);
  doc.text(actionLines, margin, y);
  y += actionLines.length * 12 + 16;

  // Quality metrics
  doc.setFont("helvetica", "bold");
  doc.text("IMAGE QUALITY METRICS", margin, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  doc.text(`Quality: ${results.quality}/100     Sharpness: ${results.sharpness}     Entropy: ${results.entropy}`, margin, y);
  y += 24;

  // Probability distribution
  doc.setFont("helvetica", "bold");
  doc.text("GRADE PROBABILITY DISTRIBUTION", margin, y);
  y += 14;
  doc.setFont("helvetica", "normal");
  results.probs.forEach((p, i) => {
    doc.text(`Grade ${i} — ${GRADES[i].name}`, margin, y);
    doc.text(`${(p * 100).toFixed(1)}%`, pageW - margin, y, { align: "right" });
    y += 13;
  });
  y += 16;

  // Footer disclaimer
  doc.setDrawColor(180);
  doc.line(margin, y, pageW - margin, y);
  y += 16;
  doc.setFontSize(8);
  doc.setTextColor(120);
  const disclaimer = "AI screening decision support only — not a clinical diagnosis. Confirm with a qualified ophthalmologist. Generated by Netra AI (SIH 26038).";
  doc.text(doc.splitTextToSize(disclaimer, pageW - margin * 2), margin, y);

  doc.save(`netra_ai_report_grade${results.grade}.pdf`);
}

const GRADES = [
  {
    name: "No DR", label: "Grade 0", urgency: "No Referral Required",
    action: "No diabetic retinopathy detected. Continue annual screening and diabetes management.",
    color: "#22C55E", textColor: "#4ADE80", bg: "rgba(34,197,94,0.07)",
  },
  {
    name: "Mild NPDR", label: "Grade 1", urgency: "Monitor — 6 Months",
    action: "Mild non-proliferative DR. Early microaneurysms noted. Schedule 6-month follow-up with improved glycaemic control.",
    color: "#A3E635", textColor: "#BEF264", bg: "rgba(163,230,53,0.07)",
  },
  {
    name: "Moderate NPDR", label: "Grade 2", urgency: "Refer — 4 to 6 Weeks",
    action: "Moderate non-proliferative DR. Multiple lesions present. Ophthalmology referral within 4–6 weeks recommended.",
    color: "#FBBF24", textColor: "#FCD34D", bg: "rgba(251,191,36,0.07)",
  },
  {
    name: "Severe NPDR", label: "Grade 3", urgency: "Urgent Referral",
    action: "Severe non-proliferative DR. Significant haemorrhages across quadrants. Urgent ophthalmology referral required.",
    color: "#F97316", textColor: "#FB923C", bg: "rgba(249,115,22,0.08)",
  },
  {
    name: "Proliferative DR", label: "Grade 4", urgency: "IMMEDIATE REFERRAL",
    action: "Sight-threatening proliferative DR. Neovascularisation detected. IMMEDIATE referral. Anti-VEGF or laser photocoagulation needed.",
    color: "#EF4444", textColor: "#F87171", bg: "rgba(239,68,68,0.09)",
  },
];

const PHASES = [
  { name: "Quality Assessment",    detail: "entropy · sharpness metrics" },
  { name: "CLAHE Enhancement",     detail: "green channel enhancement" },
  { name: "Deep Learning Grading", detail: "EfficientNet-B4 inference" },
  { name: "Grad-CAM Generation",   detail: "gradient-weighted attention mapping" },
  { name: "Finalizing Results",    detail: "compiling report & metrics" },
];

// ─── SCREENING FILTER (gatekeeper stage, runs BEFORE the DR pipeline) ────────
function checkIsRetina(imgEl) {
  const W = 200, H = 200;
  const cv = document.createElement("canvas");
  cv.width = W; cv.height = H;
  const ctx = cv.getContext("2d");
  ctx.drawImage(imgEl, 0, 0, W, H);
  const { data } = ctx.getImageData(0, 0, W, H);
  let rSum=0, gSum=0, bSum=0, aSum=0, cornerDark=0, n=0;
  const corners = [[5,5],[W-5,5],[5,H-5],[W-5,H-5]];
  for (let y=0; y<H; y+=4) {
    for (let x=0; x<W; x+=4) {
      const i = (y*W+x)*4;
      rSum+=data[i]; gSum+=data[i+1]; bSum+=data[i+2]; aSum+=data[i+3]; n++;
    }
  }
  if (aSum/n < 250) return false;
  corners.forEach(([x,y])=>{
    const i=(y*W+x)*4;
    if ((data[i]+data[i+1]+data[i+2])/3 < 40) cornerDark++;
  });
  const rAvg=rSum/n, gAvg=gSum/n, bAvg=bSum/n;
  return (rAvg > gAvg*1.15 && rAvg > bAvg*1.3) && cornerDark >= 2;
}

// ─── TINY ICONS ──────────────────────────────────────────────────────────────
const EyeIcon=()=>(
  <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth={1.8}>
    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>
    <circle cx="12" cy="12" r="3"/>
  </svg>
);
const CheckIcon=()=>(
  <svg width={12} height={12} viewBox="0 0 24 24" fill="none" stroke="#22C55E" strokeWidth={3}>
    <polyline points="20 6 9 17 4 12"/>
  </svg>
);
const SpinnerIcon=({color="#00BFFF"})=>(
  <div style={{width:13,height:13,border:`2px solid rgba(0,191,255,0.15)`,borderTopColor:color,borderRadius:"50%",animation:"drSpin 0.75s linear infinite",flexShrink:0}}/>
);

// ─── MAIN COMPONENT ──────────────────────────────────────────────────────────
export default function DRScreenAI() {
  const [stage,setStage]=useState("upload"); // upload|validating|processing|results|rejected|unsupported|apiError
  const [imgSrc,setImgSrc]=useState(null);
  const [phaseIdx,setPhaseIdx]=useState(-1);
  const [done,setDone]=useState([]);
  const [results,setResults]=useState(null);
  const [tab,setTab]=useState("original");
  const [dragging,setDragging]=useState(false);
  const [error,setError]=useState("");
  const [recapture,setRecapture]=useState(null);

  const fileRef=useRef(null);
  const timers=useRef([]);

  // Drives the phase-progress animation while the real API call is in flight.
  // The animation loops through phases; when the fetch resolves, we jump straight to results.
  const runRealPipeline = useCallback((file, dataUrl) => {
    timers.current.forEach(clearTimeout);
    timers.current = [];
    setImgSrc(dataUrl); setStage("processing"); setError("");
    setPhaseIdx(-1); setDone([]); setTab("original"); setResults(null);

    // step through phases visually every ~650ms, holding on the last phase
    // (not looping) once reached, so it never looks stuck-then-restarting
    let i = 0;
    const stepMs = 650;
    const stepper = setInterval(() => {
      const clampedIdx = Math.min(i, PHASES.length - 1);
      setPhaseIdx(clampedIdx);
      setDone(prev => {
        const next = [...prev];
        const prevIdx = i - 1;
        if (prevIdx >= 0 && prevIdx < PHASES.length - 1 && !next.includes(prevIdx)) next.push(prevIdx);
        return next;
      });
      if (i < PHASES.length - 1) i++;
    }, stepMs);
    timers.current.push(stepper);

    const formData = new FormData();
    formData.append("file", file);

    fetch(`${API_URL}/predict`, { method: "POST", body: formData })
      .then(async res => {
        if (res.status === 422) {
          const body = await res.json();
          clearInterval(stepper);
          setRecapture({ issues: body.detail?.issues || ["Image quality too low"], quality: body.detail?.quality });
          setStage("upload");
          return null;
        }
        if (!res.ok) throw new Error(`Server responded ${res.status}`);
        return res.json();
      })
      .then(data => {
        if (!data) return;
        clearInterval(stepper);
        setDone([0,1,2,3,4]);
        setPhaseIdx(4);
        setTimeout(() => {
          setResults(data);
          setStage("results");
        }, 350);
      })
      .catch(err => {
        clearInterval(stepper);
        setError(err.message || "Could not reach the model server.");
        setStage("apiError");
      });
  }, []);

  const handleFile=useCallback((file)=>{
    if(!file?.type.startsWith("image/"))return;
    const rdr=new FileReader();
    rdr.onload=e=>{
      const dataUrl=e.target.result;
      setStage("validating");
      const img=new Image();
      let settled=false;
      const timeout=setTimeout(()=>{
        if(!settled){ settled=true; setImgSrc(dataUrl); setStage("unsupported"); }
      },4000);
      img.onerror=()=>{
        if(settled)return; settled=true; clearTimeout(timeout);
        setImgSrc(dataUrl); setStage("unsupported");
      };
      img.onload=()=>{
        if(settled)return; settled=true; clearTimeout(timeout);
        const ok=checkIsRetina(img);
        if(!ok){ setImgSrc(dataUrl); setStage("rejected"); return; }
        runRealPipeline(file,dataUrl);
      };
      img.src=dataUrl;
    };
    rdr.readAsDataURL(file);
  },[runRealPipeline]);

  const reset=useCallback(()=>{
    timers.current.forEach(clearTimeout);
    setStage("upload"); setImgSrc(null); setResults(null); setPhaseIdx(-1); setDone([]); setError("");
  },[]);

  // Tokens
  const C={ bg:"#020B18", surface:"#071525", card:"#0C2040", border:"#143058", accent:"#00BFFF", text:"#E2EDF8", sub:"#6A8FAE", muted:"#2E5070" };

  return (
    <div style={{fontFamily:"'Inter',system-ui,sans-serif",background:C.bg,minHeight:"100vh",color:C.text}}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');
        @keyframes drSpin{to{transform:rotate(360deg)}}
        @keyframes drPulse{0%,100%{opacity:1}50%{opacity:0.3}}
        @keyframes drSweep{to{transform:rotate(360deg)}}
        @keyframes drFade{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
        @keyframes drScanBeam{0%{top:-25%}100%{top:125%}}
        @keyframes drRingSpin{to{transform:rotate(360deg)}}
        @keyframes drGridShift{0%{background-position-y:0}100%{background-position-y:24px}}
        @keyframes drBorderGlow{0%,100%{box-shadow:0 0 12px 1px rgba(0,191,255,0.25)}50%{box-shadow:0 0 26px 4px rgba(0,191,255,0.55)}}
        .dr-upload:hover{border-color:#00BFFF!important;background:rgba(0,191,255,0.05)!important}
        .dr-tab{transition:all .15s ease!important;cursor:pointer}
        .dr-tab:hover{border-color:#00BFFF!important;color:#00BFFF!important}
        .dr-cta:hover{filter:brightness(1.18)!important;transform:translateY(-1px)!important}
        .dr-outline:hover{border-color:#00BFFF!important;color:#E2EDF8!important}
        .dr-results-grid{display:grid;grid-template-columns:minmax(250px,1fr) minmax(270px,1.15fr);gap:22px;align-items:start;}
        .dr-processing-grid{display:grid;grid-template-columns:minmax(250px,1fr) minmax(250px,1.1fr);gap:28px;}
        @media (max-width: 768px) {
          .dr-results-grid{grid-template-columns:1fr!important;}
          .dr-processing-grid{grid-template-columns:1fr!important;}
        }
      `}</style>

      {/* ══ HEADER ══ */}
      <header style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"11px 28px",borderBottom:`1px solid ${C.border}`,background:"rgba(2,11,24,0.94)",backdropFilter:"blur(12px)",position:"sticky",top:0,zIndex:99}}>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <div style={{width:33,height:33,borderRadius:"50%",background:"radial-gradient(circle,#00BFFF 0%,#0062A8 55%,#002A60 100%)",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"0 0 14px rgba(0,191,255,0.38)"}}>
            <EyeIcon/>
          </div>
          <div>
            <div style={{fontFamily:"'Space Grotesk'",fontWeight:700,fontSize:15,letterSpacing:"-0.3px"}}>Netra <span style={{color:C.accent}}>AI</span></div>
            <div style={{fontSize:9,color:C.sub,textTransform:"uppercase",letterSpacing:"0.7px"}}>SIH 26038 · Retinopathy Screening</div>
          </div>
        </div>
        <div style={{display:"flex",alignItems:"center",gap:16}}>
          {stage!=="upload"&&<button className="dr-outline" onClick={reset} style={{padding:"6px 14px",borderRadius:7,border:`1px solid ${C.border}`,background:"transparent",color:C.sub,cursor:"pointer",fontSize:11,fontFamily:"'Inter'"}}>← New Scan</button>}
          <div style={{display:"flex",alignItems:"center",gap:6}}>
            <div style={{width:5,height:5,borderRadius:"50%",background:"#22C55E",boxShadow:"0 0 7px #22C55E",animation:"drPulse 2s ease infinite"}}/>
            <span style={{fontSize:10,color:C.sub}}>System Online</span>
          </div>
        </div>
      </header>

      <main style={{maxWidth:1080,margin:"0 auto",padding:"36px 20px"}}>

        {/* ══ VALIDATING ══ */}
        {stage==="validating"&&(
          <div style={{textAlign:"center",padding:"80px 20px",animation:"drFade 0.3s ease"}}>
            <SpinnerIcon/>
            <div style={{marginTop:14,fontSize:13,color:C.sub}}>Checking image is a valid fundus photo…</div>
          </div>
        )}

        {/* ══ UNSUPPORTED FORMAT ══ */}
        {stage==="unsupported"&&(
          <div style={{textAlign:"center",padding:"60px 20px",animation:"drFade 0.3s ease"}}>
            <div style={{fontSize:15,fontWeight:600,color:"#FBBF24",marginBottom:8}}>Image format not supported by browser</div>
            <div style={{fontSize:12,color:C.sub,marginBottom:20}}>This file (e.g. .tif/.tiff) can't be decoded by web browsers. Convert it to .jpg or .png first, then re-upload.</div>
            <button className="dr-cta" onClick={reset} style={{padding:"9px 20px",borderRadius:8,border:"none",background:C.accent,color:"#02121F",fontWeight:600,cursor:"pointer",fontSize:12}}>Try Another Image</button>
          </div>
        )}

        {/* ══ REJECTED ══ */}
        {stage==="rejected"&&(
          <div style={{textAlign:"center",padding:"60px 20px",animation:"drFade 0.3s ease"}}>
            <div style={{fontSize:15,fontWeight:600,color:"#F87171",marginBottom:8}}>Not a retinal fundus image</div>
            <div style={{fontSize:12,color:C.sub,marginBottom:20}}>The uploaded image doesn't match a fundus photo (missing red/orange retinal tone and circular vignette). Please upload a genuine retina scan.</div>
            <button className="dr-cta" onClick={reset} style={{padding:"9px 20px",borderRadius:8,border:"none",background:C.accent,color:"#02121F",fontWeight:600,cursor:"pointer",fontSize:12}}>Try Another Image</button>
          </div>
        )}

        {/* ══ API ERROR ══ */}
        {stage==="apiError"&&(
          <div style={{textAlign:"center",padding:"60px 20px",animation:"drFade 0.3s ease"}}>
            <div style={{fontSize:15,fontWeight:600,color:"#F87171",marginBottom:8}}>Couldn't reach the model server</div>
            <div style={{fontSize:12,color:C.sub,marginBottom:20}}>{error}</div>
            <button className="dr-cta" onClick={reset} style={{padding:"9px 20px",borderRadius:8,border:"none",background:C.accent,color:"#02121F",fontWeight:600,cursor:"pointer",fontSize:12}}>Try Again</button>
          </div>
        )}

        {/* ══ UPLOAD ══ */}
        {stage==="upload"&&(
          <div style={{animation:"drFade 0.4s ease"}}>
            <div style={{textAlign:"center",marginBottom:44}}>
              <div style={{display:"inline-flex",alignItems:"center",gap:6,padding:"4px 14px",borderRadius:20,background:"rgba(0,191,255,0.08)",border:"1px solid rgba(0,191,255,0.2)",fontSize:10,color:C.accent,marginBottom:22,textTransform:"uppercase",letterSpacing:"1.2px"}}>
                <div style={{width:5,height:5,borderRadius:"50%",background:C.accent,animation:"drPulse 1.5s infinite"}}/>
                AI-Powered Fundus Analysis
              </div>
              <h1 style={{fontFamily:"'Space Grotesk'",fontSize:"clamp(30px,5vw,50px)",fontWeight:700,margin:"0 0 14px",letterSpacing:"-1.2px",lineHeight:1.08,background:`linear-gradient(145deg,${C.text} 30%,${C.accent} 100%)`,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>
                Diabetic Retinopathy<br/>Screening System
              </h1>
              <p style={{color:C.sub,fontSize:13,maxWidth:420,margin:"0 auto",lineHeight:1.65}}>
                Upload a fundus image for automated AI grading with explainable Grad-CAM heatmaps — built for India's rural PHCs
              </p>
            </div>

            {recapture && (
              <div style={{maxWidth:460,margin:"0 auto 24px",padding:"14px 16px",borderRadius:10,background:"rgba(239,68,68,0.06)",border:"1px solid rgba(239,68,68,0.3)"}}>
                <div style={{fontSize:12,fontWeight:600,color:"#F87171",marginBottom:6}}>Recapture Needed — Quality {recapture.quality}/100</div>
                <ul style={{margin:0,paddingLeft:18,fontSize:11,color:C.sub}}>
                  {recapture.issues.map((iss,i)=><li key={i}>{iss}</li>)}
                </ul>
              </div>
            )}

            <div
              className="dr-upload"
              onDragOver={e=>{e.preventDefault();setDragging(true);}}
              onDragLeave={()=>setDragging(false)}
              onDrop={e=>{e.preventDefault();setDragging(false);handleFile(e.dataTransfer.files[0]);}}
              onClick={()=>fileRef.current?.click()}
              style={{borderRadius:14,border:`2px dashed ${dragging?C.accent:C.border}`,padding:"52px 32px",textAlign:"center",cursor:"pointer",background:dragging?"rgba(0,191,255,0.05)":"rgba(7,21,37,0.5)",transition:"all .2s ease",marginBottom:28,position:"relative",overflow:"hidden"}}
            >
              {[220,320,420].map((s,i)=>(
                <div key={i} style={{position:"absolute",top:"50%",left:"50%",width:s,height:s,borderRadius:"50%",border:`1px solid rgba(0,191,255,${0.04-i*0.01})`,transform:"translate(-50%,-50%)",pointerEvents:"none"}}/>
              ))}
              <div style={{width:56,height:56,borderRadius:"50%",background:"rgba(0,191,255,0.07)",border:"1px solid rgba(0,191,255,0.2)",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 18px"}}>
                <svg width={26} height={26} viewBox="0 0 24 24" fill="none" stroke={C.accent} strokeWidth={1.5}>
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M17 8l-5-5-5 5M12 3v12"/>
                </svg>
              </div>
              <div style={{fontFamily:"'Space Grotesk'",fontSize:17,fontWeight:600,marginBottom:6}}>Drop fundus image here</div>
              <div style={{color:C.sub,fontSize:12,marginBottom:18}}>JPG · PNG accepted</div>
              <div style={{display:"inline-block",padding:"7px 18px",borderRadius:7,background:"rgba(0,191,255,0.1)",border:"1px solid rgba(0,191,255,0.25)",fontSize:12,color:C.accent,fontWeight:500}}>Browse Files</div>
              <input ref={fileRef} type="file" accept="image/*" style={{display:"none"}} onChange={e=>handleFile(e.target.files[0])}/>
            </div>

            <div style={{display:"flex",flexWrap:"wrap",justifyContent:"center",gap:8,paddingTop:28,borderTop:`1px solid ${C.border}`}}>
              {[["🧠","EfficientNet-B4"],["🔥","Grad-CAM XAI"],["📡","PHC Optimized"]].map(([ic,lb])=>(
                <div key={lb} style={{display:"flex",alignItems:"center",gap:7,padding:"7px 14px",borderRadius:20,border:`1px solid ${C.border}`,background:"rgba(12,32,64,0.4)",fontSize:11,color:C.sub}}>
                  <span>{ic}</span><span>{lb}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ══ PROCESSING ══ */}
        {stage==="processing"&&(
          <div className="dr-processing-grid" style={{animation:"drFade .35s ease"}}>
            <div>
              <div style={{fontSize:10,color:C.sub,textTransform:"uppercase",letterSpacing:"1px",marginBottom:10}}>Input Fundus Image</div>
              <div style={{borderRadius:12,overflow:"hidden",border:`1px solid ${C.border}`,aspectRatio:"1",background:"#000",position:"relative",animation:"drBorderGlow 2.6s ease-in-out infinite"}}>
                <img src={imgSrc} alt="" style={{width:"100%",height:"100%",objectFit:"cover",opacity:.75,filter:"saturate(1.15)"}}/>

                {/* Scanline grid texture, slowly drifting */}
                <div style={{position:"absolute",inset:0,pointerEvents:"none",backgroundImage:`repeating-linear-gradient(to bottom, transparent 0px, transparent 3px, rgba(0,191,255,0.07) 4px)`,animation:"drGridShift 1.4s linear infinite"}}/>

                {/* Spinning conic ring around the edge */}
                <div style={{position:"absolute",inset:-2,borderRadius:"50%",padding:2,pointerEvents:"none"}}>
                  <div style={{width:"100%",height:"100%",borderRadius:"50%",background:`conic-gradient(from 0deg, transparent 0%, ${C.accent} 12%, transparent 26%)`,animation:"drRingSpin 1.8s linear infinite",WebkitMask:"radial-gradient(farthest-side, transparent calc(100% - 3px), #000 calc(100% - 3px))",mask:"radial-gradient(farthest-side, transparent calc(100% - 3px), #000 calc(100% - 3px))"}}/>
                </div>

                {[0.36,0.52,0.68].map((r,i)=>(
                  <div key={i} style={{position:"absolute",top:"50%",left:"50%",width:`${r*100}%`,height:`${r*100}%`,borderRadius:"50%",border:`1px solid rgba(0,191,255,${0.22-i*0.05})`,transform:"translate(-50%,-50%)"}}/>
                ))}
                <div style={{position:"absolute",top:"50%",left:"50%",width:"68%",height:"68%",borderRadius:"50%",transform:"translate(-50%,-50%)",animation:"drSweep 1.6s linear infinite",transformOrigin:"center"}}>
                  <div style={{position:"absolute",top:"50%",left:"50%",width:"50%",height:"2px",background:`linear-gradient(to right,${C.accent}FF,transparent)`,transformOrigin:"left center",boxShadow:`0 0 8px ${C.accent}`}}/>
                </div>
                <div style={{position:"absolute",top:"50%",left:"50%",width:7,height:7,borderRadius:"50%",background:C.accent,boxShadow:`0 0 16px 4px ${C.accent}`,transform:"translate(-50%,-50%)",animation:"drPulse .8s infinite"}}/>

                {/* Bright horizontal scanning beam sweeping top to bottom */}
                <div style={{position:"absolute",left:0,right:0,height:"22%",background:`linear-gradient(to bottom, transparent, ${C.accent}22, ${C.accent}88, ${C.accent}22, transparent)`,animation:"drScanBeam 1.9s ease-in-out infinite",pointerEvents:"none",filter:"blur(1px)"}}/>
                <div style={{position:"absolute",left:0,right:0,height:2,background:C.accent,boxShadow:`0 0 20px 5px ${C.accent}`,animation:"drScanBeam 1.9s ease-in-out infinite",pointerEvents:"none"}}/>

                <div style={{position:"absolute",top:10,left:10,width:16,height:16,borderTop:`2px solid ${C.accent}`,borderLeft:`2px solid ${C.accent}`,opacity:.9,animation:"drPulse 1.6s infinite"}}/>
                <div style={{position:"absolute",top:10,right:10,width:16,height:16,borderTop:`2px solid ${C.accent}`,borderRight:`2px solid ${C.accent}`,opacity:.9,animation:"drPulse 1.6s infinite"}}/>
                <div style={{position:"absolute",bottom:10,left:10,width:16,height:16,borderBottom:`2px solid ${C.accent}`,borderLeft:`2px solid ${C.accent}`,opacity:.9,animation:"drPulse 1.6s infinite"}}/>
                <div style={{position:"absolute",bottom:10,right:10,width:16,height:16,borderBottom:`2px solid ${C.accent}`,borderRight:`2px solid ${C.accent}`,opacity:.9,animation:"drPulse 1.6s infinite"}}/>
                <div style={{position:"absolute",bottom:10,left:12,fontSize:8,color:C.accent,fontFamily:"'JetBrains Mono'",letterSpacing:"1.2px",animation:"drPulse 1.2s infinite"}}>ANALYZING RETINA...</div>
              </div>
            </div>

            <div>
              <div style={{fontSize:10,color:C.sub,textTransform:"uppercase",letterSpacing:"1px",marginBottom:10}}>AI Pipeline Progress</div>
              <div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:20}}>
                {PHASES.map((ph,i)=>{
                  const isActive=phaseIdx===i, isDone=done.includes(i);
                  return(
                    <div key={i} style={{padding:"12px 13px",borderRadius:10,border:`1px solid ${isDone?"rgba(34,197,94,0.32)":isActive?C.accent+"88":C.border}`,background:isDone?"rgba(34,197,94,0.04)":isActive?"rgba(0,191,255,0.07)":"rgba(12,32,64,0.35)",opacity:!isActive&&!isDone?.38:1,transition:"all .35s ease",display:"flex",alignItems:"center",gap:11}}>
                      <div style={{width:25,height:25,borderRadius:"50%",flexShrink:0,border:`1px solid ${isDone?"#22C55E":isActive?C.accent:C.border}`,background:isDone?"rgba(34,197,94,0.12)":isActive?"rgba(0,191,255,0.12)":"rgba(255,255,255,0.03)",display:"flex",alignItems:"center",justifyContent:"center"}}>
                        {isDone?<CheckIcon/>:isActive?<SpinnerIcon/>:<span style={{fontFamily:"'JetBrains Mono'",fontSize:9,color:C.muted}}>{i+1}</span>}
                      </div>
                      <div style={{flex:1,minWidth:0}}>
                        <div style={{fontSize:12,fontWeight:600,color:isDone?"#4ADE80":isActive?C.text:C.sub}}>{ph.name}</div>
                        <div style={{fontSize:9,color:C.muted,fontFamily:"'JetBrains Mono'",marginTop:1,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{ph.detail}</div>
                      </div>
                      {(isDone||isActive)&&<div style={{fontSize:9,fontWeight:600,flexShrink:0,color:isDone?"#22C55E":C.accent,textTransform:"uppercase",letterSpacing:".5px"}}>{isDone?"✓ done":"running"}</div>}
                    </div>
                  );
                })}
              </div>
              <div style={{fontSize:10,color:C.sub,display:"flex",justifyContent:"space-between",marginBottom:6}}>
                <span>Pipeline Progress</span>
                <span style={{fontFamily:"'JetBrains Mono'"}}>{Math.round(done.length/PHASES.length*100)}%</span>
              </div>
              <div style={{height:5,background:C.border,borderRadius:3,overflow:"hidden"}}>
                <div style={{height:"100%",width:`${done.length/PHASES.length*100}%`,background:`linear-gradient(90deg,#0070BB,${C.accent})`,transition:"width .5s ease",boxShadow:`0 0 8px ${C.accent}55`}}/>
              </div>
            </div>
          </div>
        )}

        {/* ══ RESULTS ══ */}
        {stage==="results"&&results&&(()=>{
          const G=GRADES[results.grade];
          return(
            <div style={{animation:"drFade .5s ease"}}>
              <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:24}}>
                <div>
                  <h2 style={{fontFamily:"'Space Grotesk'",fontSize:20,fontWeight:700,margin:0}}>Analysis Complete</h2>
                  <div style={{fontSize:11,color:C.sub,marginTop:2}}>EfficientNet-B4 · Grad-CAM (real inference)</div>
                </div>
                <button className="dr-outline" onClick={reset} style={{padding:"7px 16px",borderRadius:8,border:`1px solid ${C.border}`,background:"transparent",color:C.sub,cursor:"pointer",fontSize:11,fontFamily:"'Inter'"}}>← New Scan</button>
              </div>

              <div className="dr-results-grid">
                {/* LEFT: Image viewer */}
                <div>
                  <div style={{display:"flex",gap:4,marginBottom:10}}>
                    {[["original","Original"],["enhanced","Enhanced"],["vessels","Vessels"],["heatmap","Grad-CAM"]].map(([id,lb])=>(
                      <button key={id} className="dr-tab" onClick={()=>setTab(id)} style={{padding:"5px 12px",borderRadius:6,border:`1px solid ${tab===id?C.accent:C.border}`,background:tab===id?"rgba(0,191,255,0.1)":"transparent",color:tab===id?C.accent:C.sub,fontSize:10,fontWeight:500,fontFamily:"'Inter'"}}>
                        {lb}
                      </button>
                    ))}
                  </div>

                  <div style={{borderRadius:12,overflow:"hidden",border:`1px solid ${C.border}`,background:"#000",aspectRatio:"1",position:"relative"}}>
                    <img
                      src={tab==="enhanced"?results.enhanced:tab==="vessels"?results.vessels:tab==="heatmap"?results.heatmap:imgSrc}
                      alt="Fundus"
                      style={{width:"100%",height:"100%",objectFit:"cover"}}
                    />
                    <div style={{position:"absolute",top:9,left:9,padding:"3px 8px",borderRadius:4,background:"rgba(0,0,0,0.65)",backdropFilter:"blur(6px)",fontSize:8,color:C.accent,textTransform:"uppercase",letterSpacing:"1px",fontFamily:"'JetBrains Mono'"}}>
                      {tab==="enhanced"?"CLAHE Enhanced":tab==="vessels"?"Frangi Vessel Enhancement":tab==="heatmap"?"Grad-CAM Attention":"Original Fundus"}
                    </div>
                  </div>

                  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginTop:10}}>
                    {[{l:"Quality",v:`${results.quality}%`,ok:results.quality>75},{l:"Sharpness",v:results.sharpness,ok:Number(results.sharpness)>100},{l:"Entropy",v:results.entropy,ok:Number(results.entropy)>5.5}].map(m=>(
                      <div key={m.l} style={{padding:"9px 8px",borderRadius:8,textAlign:"center",background:"rgba(12,32,64,0.55)",border:`1px solid ${C.border}`}}>
                        <div style={{fontFamily:"'JetBrains Mono'",fontSize:13,fontWeight:500,color:m.ok?"#4ADE80":"#FCD34D"}}>{m.v}</div>
                        <div style={{fontSize:9,color:C.sub,marginTop:2,textTransform:"uppercase",letterSpacing:".4px"}}>{m.l}</div>
                      </div>
                    ))}
                  </div>
                  {tab==="vessels" && (
                    <p style={{fontSize:10,color:C.muted,marginTop:8,lineHeight:1.5}}>
                      Frangi vesselness filter — a classical image-processing technique that highlights tubular structures, not a trained segmentation model. Full vessel/lesion segmentation is a planned Phase 2 item.
                    </p>
                  )}
                </div>

                {/* RIGHT: Results panel */}
                <div style={{display:"flex",flexDirection:"column",gap:13}}>
                  <div style={{padding:20,borderRadius:12,background:G.bg,border:`1px solid ${G.color}38`}}>
                    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:13}}>
                      <div>
                        <div style={{fontSize:9,color:C.sub,textTransform:"uppercase",letterSpacing:"1px",marginBottom:6}}>DR Severity Grade</div>
                        <div style={{fontFamily:"'Space Grotesk'",fontSize:27,fontWeight:700,color:G.textColor,lineHeight:1}}>{G.name}</div>
                        <div style={{fontSize:11,color:C.sub,marginTop:3}}>{G.label}</div>
                      </div>
                      <div style={{textAlign:"right"}}>
                        <div style={{fontSize:9,color:C.sub,marginBottom:4}}>AI Confidence</div>
                        <div style={{fontFamily:"'JetBrains Mono'",fontSize:25,fontWeight:600,color:G.color}}>{(results.confidence*100).toFixed(1)}%</div>
                      </div>
                    </div>
                    <div style={{height:5,background:"rgba(0,0,0,0.3)",borderRadius:3,overflow:"hidden",marginBottom:13}}>
                      <div style={{height:"100%",width:`${results.confidence*100}%`,background:G.color,borderRadius:3,boxShadow:`0 0 8px ${G.color}72`,transition:"width 1.2s ease"}}/>
                    </div>
                    <span style={{display:"inline-flex",alignItems:"center",gap:6,padding:"5px 12px",borderRadius:6,background:`${G.color}18`,border:`1px solid ${G.color}45`,fontSize:10,fontWeight:700,color:G.color,textTransform:"uppercase",letterSpacing:".5px"}}>
                      {results.grade>=3&&<div style={{width:6,height:6,borderRadius:"50%",background:G.color,animation:"drPulse .8s infinite"}}/>}
                      {G.urgency}
                    </span>
                  </div>

                  <div style={{padding:"13px 15px",borderRadius:10,background:"rgba(12,32,64,0.55)",border:`1px solid ${C.border}`}}>
                    <div style={{fontSize:9,color:C.sub,textTransform:"uppercase",letterSpacing:"1px",marginBottom:7}}>Clinical Recommendation</div>
                    <div style={{fontSize:12,color:C.text,lineHeight:1.6}}>{G.action}</div>
                  </div>

                  <div style={{padding:"13px 15px",borderRadius:10,background:"rgba(12,32,64,0.55)",border:`1px solid ${C.border}`}}>
                    <div style={{fontSize:9,color:C.sub,textTransform:"uppercase",letterSpacing:"1px",marginBottom:12}}>Grade Probability Distribution</div>
                    {results.probs.map((p,i)=>(
                      <div key={i} style={{marginBottom:i<4?9:0}}>
                        <div style={{display:"flex",justifyContent:"space-between",marginBottom:3}}>
                          <span style={{fontSize:10,fontWeight:i===results.grade?600:400,color:i===results.grade?GRADES[i].color:C.sub}}>G{i} — {GRADES[i].name}</span>
                          <span style={{fontFamily:"'JetBrains Mono'",fontSize:9,color:i===results.grade?GRADES[i].color:C.muted}}>{(p*100).toFixed(1)}%</span>
                        </div>
                        <div style={{height:4,background:"rgba(255,255,255,0.05)",borderRadius:2,overflow:"hidden"}}>
                          <div style={{height:"100%",width:`${p*100}%`,background:i===results.grade?GRADES[i].color:`${GRADES[i].color}45`,borderRadius:2,transition:`width ${1+i*.1}s ease`}}/>
                        </div>
                      </div>
                    ))}
                  </div>

                  <div style={{padding:"13px 15px",borderRadius:10,background:"rgba(0,191,255,0.04)",border:"1px solid rgba(0,191,255,0.14)",display:"flex",gap:11}}>
                    <div style={{fontSize:17,flexShrink:0}}>🔥</div>
                    <div>
                      <div style={{fontSize:10,fontWeight:600,color:C.accent,marginBottom:4}}>Grad-CAM Explanation</div>
                      <div style={{fontSize:11,color:C.sub,lineHeight:1.55}}>Real gradient-weighted attention map from the trained model, highlighting the regions that most influenced this grade. Lesion-level biomarkers (MA/exudate counts) require the segmentation model — planned for Phase 2.</div>
                    </div>
                  </div>

                  <button
                    className="dr-cta"
                    onClick={()=>generatePdfReport(results, imgSrc, G)}
                    style={{width:"100%",padding:"12px",borderRadius:10,background:`linear-gradient(130deg,#005A99,${C.accent})`,border:"none",color:"white",cursor:"pointer",fontSize:13,fontWeight:600,fontFamily:"'Space Grotesk'",boxShadow:"0 4px 20px rgba(0,191,255,0.22)",transition:"all .2s ease"}}
                  >
                    ↓ Download PDF Report
                  </button>
                </div>
              </div>
            </div>
          );
        })()}
      </main>
    </div>
  );
}